HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Controllers/AdminHallController.cs
namespace HRAgencySystem.Web.Areas.Admin.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Net;
    using AutoMapper.QueryableExtensions;

    using HRAgencySystem.Data.DataLayer;
    using HRAgencySystem.Models;
    using HRAgencySystem.Web.Areas.Admin.InputModels.Hall;
    using HRAgencySystem.Web.Areas.Admin.ViewModels.Hall;
    using HRAgencySystem.Web.Controllers;
    using HRAgencySystem.Web.ViewModels.Hall;
    using HRAgencySystem.Web.ViewModels.Reservation;

    [Authorize(Roles = "Admin")]
    [Route("Admin/Hall")]
    public class AdminHallController : BaseController
    {
        public AdminHallController(IHRAgancyData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Add()
        {
            this.LoadItems();
            this.LoadOffices();
            this.LoadStatuses();

            return View();
        }

        [HttpPost]
        public ActionResult Add(HallInputModel model)
        {
            var isHaveHallWithSameName = this.Data.Halls.All().FirstOrDefault(h => h.Name == model.Name) != null;
            if (model != null && this.ModelState.IsValid && !isHaveHallWithSameName)
            {
                List<Item> items = new List<Item>();
                foreach (var itemId in model.ItemIds)
                {
                    items.Add(this.Data.Items.All().FirstOrDefault(i => i.Id == itemId));
                }

                var hall = new Hall()
                {
                    Name = model.Name,
                    Description = model.Description,
                    OfficeId = this.Data.Offices.All().Where(o => o.Id == model.OfficeId).Select(o => o.Id).FirstOrDefault(),
                    Capacity = model.Capacity,
                    HallStatusId = this.Data.HallStatuses.All().Where(s => s.Id == model.HallStatusId).Select(s => s.Id).FirstOrDefault(),
                    Items = items
                };

                this.Data.Halls.Add(hall);
                this.Data.SaveChanges();
            }

            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var hall = this.Data.Halls
                .All()
                .ProjectTo<HallDetailsViewModel>()
                .FirstOrDefault(h => h.Id == id);

            var reservaitons = this.Data.Reservations
               .All()
               .Where(r => r.HallId == id)
               .ProjectTo<ReservationViewModel>()
               .ToList();

            this.LoadItems();

            var model = new DeleteHallViewModel()
            {
                Hall = hall,
                Reservations = reservaitons
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteHall(int id)
        {
            var hall = this.Data.Halls
               .All()
               .FirstOrDefault(h => h.Id == id);

            var reservaitons = this.Data.Reservations
               .All()
               .Where(r => r.HallId == id)
               .ToList();

            if (hall != null)
            {
                if (reservaitons.Any())
                {
                    foreach (var reservation in reservaitons)
                    {
                        this.Data.Reservations.Delete(reservation);
                    }
                }

                this.Data.Halls.Delete(hall);
                this.Data.SaveChanges();

                return this.RedirectToAction("Index", "Home", new { area = "" });
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Cannot delete this hall!");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            this.LoadCurrentHall(id);
            this.LoadOffices();
            this.LoadStatuses();

            return this.View();
        }

        [HttpPost]
        public ActionResult Edit(int id, EditHallInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var hall = this.Data.Halls
                .All()
                .FirstOrDefault(h => h.Id == id);

                if (hall != null)
                {
                    hall.Name = model.Name;
                    hall.Capacity = model.Capacity;
                    hall.Description = model.Description;
                    hall.HallStatusId = model.HallStatusId;
                    hall.OfficeId = model.OfficeId;

                    this.Data.Halls.Update(hall);
                    this.Data.SaveChanges();
                }

                return this.RedirectToAction("Index", "Home", new { area = "" });
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Cannot edit this hall!");
        }

        private void LoadCurrentHall(int hallId)
        {
            ViewBag.CurrHall = this.Data.Halls
                .All()
                .Where(h => h.HallStatus.Name == "Active")
                .ProjectTo<HallDetailsViewModel>()
                .FirstOrDefault(h => h.Id == hallId);
        }

        private void LoadItems()
        {
            this.ViewBag.Items = this.Data.Items
                .All()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
        }

        private void LoadOffices()
        {
            this.ViewBag.Offices = this.Data.Offices
                .All()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
        }

        private void LoadStatuses()
        {
            this.ViewBag.Statuses = this.Data.HallStatuses
                .All()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
        }
    }
}

HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Views/AdminHall/Add.cshtml
@model HRAgencySystem.Web.Areas.Admin.InputModels.Hall.HallInputModel
@{
    ViewBag.Title = "Create Hall";
}

<h2>Create Hall</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true) // don't show my exception from my properaties

    @Html.LabelFor(x => x.Name, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control", @type = "text" } });
    @Html.ValidationMessageFor(x => x.Name);
    <br />
    @Html.LabelFor(x => x.Description, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @type = "textarea" } });
    @Html.ValidationMessageFor(x => x.Description);
    <br/>
    @Html.LabelFor(x => x.Capacity, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Capacity, new { htmlAttributes = new { @class = "form-control", @type = "textarea" } });
    @Html.ValidationMessageFor(x => x.Capacity);
    <br />
    @Html.LabelFor(x => x.OfficeId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.OfficeId, (IEnumerable<SelectListItem>)ViewBag.Offices, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.OfficeId);
    <br/>
    @Html.LabelFor(x => x.HallStatusId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.HallStatusId, (IEnumerable<SelectListItem>)ViewBag.Statuses, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.HallStatusId);
    <br />
    @Html.LabelFor(x => x.Items, new { @class = "col-md-2 control-label" })
    @Html.ListBoxFor(x => Model.ItemIds, (IEnumerable<SelectListItem>)ViewBag.Items, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Items);
    <br/>

    <input type="submit" name="submit" value="Add Hall" class="btn btn-primary" />
}

@*Javascript errors for create form*@

@section scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Views/AdminHall/AddHall.cshtml
@model HRAgencySystem.Web.Areas.InputModels.Hall.HallInputModel
@{
    ViewBag.Title = "Create Hall";
}

<h2>Create Hall</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true) // don't show my exception from my properaties

    @Html.LabelFor(x => x.Name, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control", @type = "text" } });
    @Html.ValidationMessageFor(x => x.Name);
    <br />
    @Html.LabelFor(x => x.Description, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @type = "textarea" } });
    @Html.ValidationMessageFor(x => x.Description);
    <br/>
    @Html.LabelFor(x => x.Capacity, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Capacity, new { htmlAttributes = new { @class = "form-control", @type = "textarea" } });
    @Html.ValidationMessageFor(x => x.Capacity);
    <br />
    @Html.LabelFor(x => x.OfficeId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.OfficeId, (IEnumerable<SelectListItem>)ViewBag.Offices, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.OfficeId);
    <br/>
    @Html.LabelFor(x => x.HallStatusId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.HallStatusId, (IEnumerable<SelectListItem>)ViewBag.Statuses, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.HallStatusId);
    <br />
    @Html.LabelFor(x => x.Items, new { @class = "col-md-2 control-label" })
    @Html.ListBoxFor(x => Model.ItemIds, (IEnumerable<SelectListItem>)ViewBag.Items, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Items);
    <br/>

    <input type="submit" name="submit" value="Add Hall" class="btn btn-primary" />
}

@*Javascript errors for create form*@

@section scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Views/AdminHall/Delete.cshtml
@model HRAgencySystem.Web.Areas.Admin.ViewModels.Hall.DeleteHallViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Hall</h2>
<div id="delete-hall">
    @using (Html.BeginForm("DeleteHall", "AdminHall", new {id = @Model.Hall.Id}, FormMethod.Post))
    {
        @Html.LabelFor(x => x.Hall.Name, new { @class = "col-md-2 control-label" });
        @Html.EditorFor(x => x.Hall.Name, new { htmlAttributes = new { @class = "form-control", @type = "text", @readonly = "readonly" } });
        <br />
        @Html.LabelFor(x => x.Hall.Description, new { @class = "col-md-2 control-label" });
        @Html.EditorFor(x => x.Hall.Description, new { htmlAttributes = new { @class = "form-control", @type = "textarea", @readonly = "readonly" } });
        <br />
        @Html.LabelFor(x => x.Hall.Capacity, new { @class = "col-md-2 control-label" });
        @Html.EditorFor(x => x.Hall.Capacity, new { htmlAttributes = new { @class = "form-control", @type = "text", @readonly = "readonly" } });
        <br />
        @Html.LabelFor(x => x.Hall.OfficeName, new { @class = "col-md-2 control-label" });
        @Html.EditorFor(x => x.Hall.OfficeName, new { htmlAttributes = new { @class = "form-control", @type = "text", @readonly = "readonly" } });
        <br />
        @Html.LabelFor(x => x.Hall.Items, new { @class = "col-md-2 control-label" });
        @Html.DropDownListFor(x => x.Hall.Items, (IEnumerable<SelectListItem>)ViewBag.Items, new { @class = "form-control", @readonly = "readonly" });
        <br />

        <input type="submit" name="submit" value="Delete" class="btn btn-danger" />
    }

    <div id="hall-reservation-info">
        <h2>You will delete this reservations:</h2>
        @if (@Model.Reservations.Any())
        {
            <table border="1" id="hall-reservations-table" class="table-hover table-user-reservations">
                <thead>
                    <tr>
                        <th class="hidden-phone">Hall name</th>
                        <th>Description</th>
                        <th>Capacity</th>
                       <th></th>
                    </tr>
                </thead>
                <tbody>
                    @Html.DisplayFor(x => x.Reservations)
                </tbody>
            </table>
        }
        else
        {
            <p>No reservations!</p>
        }
    </div>
</div>

HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Views/AdminHall/Edit.cshtml
@model HRAgencySystem.Web.Areas.Admin.InputModels.Hall.EditHallInputModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit hall:</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true) // don't show my exception from my properaties

    @Html.LabelFor(x => x.Name, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control", @type = "text", @Value = ViewBag.CurrHall.Name } });
    @Html.ValidationMessageFor(x => x.Name);
    <br />
    @Html.LabelFor(x => x.Description, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @type = "textarea", @Value = ViewBag.CurrHall.Description } });
    @Html.ValidationMessageFor(x => x.Description);
    <br />
    @Html.LabelFor(x => x.Capacity, new { @class = "col-md-2 control-label" });
    @Html.EditorFor(x => x.Capacity, new { htmlAttributes = new { @class = "form-control", @type = "textarea", @Value = ViewBag.CurrHall.Capacity } });
    @Html.ValidationMessageFor(x => x.Capacity);
    <br />
    @Html.LabelFor(x => x.OfficeId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.OfficeId, (IEnumerable<SelectListItem>)ViewBag.Offices, new { @class = "form-control", @Value = ViewBag.CurrHall.OfficeName });
    @Html.ValidationMessageFor(x => x.OfficeId);
    <br />
    @Html.LabelFor(x => x.HallStatusId, new { @class = "col-md-2 control-label" });
    @Html.DropDownListFor(x => x.HallStatusId, (IEnumerable<SelectListItem>)ViewBag.Statuses, new { @class = "form-control", @Value = ViewBag.CurrHall.HallStatusName });
    @Html.ValidationMessageFor(x => x.HallStatusId);
    <br />

    <input type="submit" name="submit" value="Edit Hall" class="btn btn-primary" />
}

@*Javascript errors for create form*@

@section scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}