HRAgencySystem/HRAgencySystem.Web/Areas/Admin/ViewModels/Hall/DeleteHallViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HRAgencySystem.Web.ViewModels.Hall;
using HRAgencySystem.Web.ViewModels.Reservation;

namespace HRAgencySystem.Web.Areas.Admin.ViewModels.Hall
{
    public class DeleteHallViewModel
    {
        public HallDetailsViewModel Hall { get; set; }

        public IEnumerable<ReservationViewModel> Reservations { get; set; }
    }
}

HRAgencySystem/HRAgencySystem.Web/ViewModels/Hall/HallDetailsViewModel.cs
namespace HRAgencySystem.Web.ViewModels.Hall
{
    using System.Collections.Generic;

    using AutoMapper;

    using HRAgencySystem.Web.ViewModels.Item;
    using HRAgencySystem.Common.Mappings;
    using HRAgencySystem.Models;

    public class HallDetailsViewModel : IMapFrom<Hall>
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Capacity { get; set; }

        public string OfficeName { get; set; }

        public string HallStatusName { get; set; }

        public IEnumerable<ItemViewModel> Items { get; set; }
    }
}

HRAgencySystem/HRAgencySystem.Web/ViewModels/Hall/HallReservationsViewModel.cs
namespace HRAgencySystem.Web.ViewModels.Hall
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using HRAgencySystem.Common.Mappings;
    using HRAgencySystem.Models;

    public class HallReservationsViewModel : IMapFrom<Reservation>
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public string HallName { get; set; }

        public int CapacityForReservation { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }
    }
}

HRAgencySystem/HRAgencySystem.Web/ViewModels/Hall/HallViewModel.cs
namespace HRAgencySystem.Web.ViewModels.Hall
{
    using Common.Mappings;
    using HRAgencySystem.Models;

    public class HallViewModel : IMapFrom<Hall>
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Capacity { get; set; }
    }
}

HRAgencySystem/HRAgencySystem.Web/Areas/Admin/Controllers/AdminReservationController.cs
using System;

namespace HRAgencySystem.Web.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using System.Linq;
    using System.Collections.Generic;

    using AutoMapper;
    using HRAgencySystem.Models;
    using HRAgencySystem.Data.DataLayer;
    using HRAgencySystem.Web.Areas.Admin.InputModels.Reservation;
    using HRAgencySystem.Web.Controllers;

    [Authorize(Roles = "Admin")]
    [Route("Admin/Reservation")]
    public class AdminReservationController : BaseController
    {
        public AdminReservationController(IHRAgancyData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult CreateReservation()
        {
            this.LoadHalls();
            this.LoadUsers();
            return View("~/Areas/Admin/Views/Reservation/CreateReservation.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReservation(ReservationInputModel model)
        {
            var getHallReservations = this.Data.Reservations.All()
                    .Where(r => r.HallId == model.HallId);

            bool isHaveReservation = false;
            foreach (var hallReservation in getHallReservations)
            {
                // Check is have reservation that is between input date of reservation
                if ((model.StartDate <= hallReservation.StartDate && model.EndDate >= hallReservation.EndDate))
                {
                    isHaveReservation = true;
                }

                // Check is input start date is detected with one of the dates and check if input end date is detected with one of the dates
                if ((model.StartDate <= hallReservation.EndDate && model.StartDate >= hallReservation.StartDate) ||
                    (model.EndDate >= hallReservation.StartDate && model.EndDate <= hallReservation.EndDate))
                {
                    isHaveReservation = true;
                }
            }

            // You can reserve a hall not less for hour
            bool isStartDateLowerWithAnHour = model.StartDate.AddHours(1) <= model.EndDate;

            // You can reserve a hall one hour before current time
            bool isPiriodIsBiggerThanCurrentDate = model.StartDate >= DateTime.Now.AddHours(1);

            if (model != null && 
                this.ModelState.IsValid && 
                isStartDateLowerWithAnHour &&
                isPiriodIsBiggerThanCurrentDate &&
                (!isHaveReservation))
            {

                List<User> users = new List<User>();
                foreach (var userId in model.UserIds)
                {
                    users.Add(this.Data.Users.All().FirstOrDefault(u => u.Id == userId));
                }

                var currentHall = this.Data.Halls.All().FirstOrDefault(h => h.Id == model.HallId);

                //Check is have enough capacity for users;
                bool isHaveCapacity = currentHall.Capacity >= users.Count();
                if (isHaveCapacity)
                {
                    var reservation = new Reservation
                    {
                        Description = model.Description,
                        HallId =
                            this.Data.Halls.All()
                                .Where(h => h.Id == model.HallId)
                                .Select(h => h.Id)
                                .FirstOrDefault(),
                        Users = users,
                        StartDate = model.StartDate,
                        EndDate = model.EndDate,
                        CapacityForReservation = currentHall.Capacity - users.Count()
                    };

                    this.Data.Reservations.Add(reservation);
                    this.Data.SaveChanges();
                }
            }

            return this.RedirectToAction("Index", "Home", new { area = "" });


            //When we return model we will show the errors
            return this.View(model);
        }

        private void LoadHalls()
        {
            this.ViewBag.Halls = this.Data.Halls
                .All()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
        }

        private void LoadUsers()
        {
            this.ViewBag.Users = this.Data.Users
                .All()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.UserName
                });
        }
    }
}

HRAgencySystem/HRAgencySystem.Web/Controllers/HallController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using HRAgencySystem.Common;
using HRAgencySystem.Data.DataLayer;
using HRAgencySystem.Models;
using HRAgencySystem.Web.ViewModels.Hall;
using Microsoft.AspNet.Identity;
using PagedList;

namespace HRAgencySystem.Web.Controllers
{
    public class HallController : BaseController
    {
        public HallController(IHRAgancyData data) 
            : base(data)
        {
        }

        [HttpGet]
        [Authorize]
        public ActionResult Details(int id)
        {
            var hall = this.Data.Halls
                .All()
                .Include(h => h.Items)
                .Where(h => h.HallStatus.Name == "Active")
                .FirstOrDefault(h => h.Id == id);

            var hallDetailsViewModel = Mapper.Map<HallDetailsViewModel>(hall);

            return View(hallDetailsViewModel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult ShowReservations(int id, int? page)
        {
            var getHallReservations = this.Data.Reservations
                .All()
                .Where(r => r.HallId == id)
                .OrderBy(r => r.StartDate)
                .ToList();

            List<HallReservationsViewModel> hallReservations= new List<HallReservationsViewModel>();
            foreach (var hallReservation in getHallReservations)
            {
                var hallReservationVewModel = Mapper.Map<HallReservationsViewModel>(hallReservation);
                hallReservations.Add(hallReservationVewModel);
            }
            return View(hallReservations);
        }
    }
}

HRAgencySystem/HRAgencySystem.Web/Views/Hall/Details.cshtml
 @model HRAgencySystem.Web.ViewModels.Hall.HallDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

<div>
    <p>@Html.DisplayNameFor(x => x.Description) : @Html.DisplayFor(x => x.Description)</p>
    <p>@Html.DisplayNameFor(x => x.Capacity) : @Html.DisplayFor(x => x.Capacity)</p>
    <p>@Html.DisplayNameFor(x => x.OfficeName) : @Html.DisplayFor(x => x.OfficeName)</p>
    <p>@Html.DisplayNameFor(x => x.HallStatusName) : @Html.DisplayFor(x => x.HallStatusName)</p>
</div>
<div id="Items">
    <h2>Items</h2>
    @if (@Model.Items.Any())
    {
        @Html.DisplayFor(x => x.Items)
    }
    else
    {
        <span>No Items</span>
    }
</div>
<p>
    @Ajax.ActionLink("Show reservations", "ShowReservations", "Hall", new {id = Model.Id}, new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "hall-reservations",
        InsertionMode = InsertionMode.Replace,
    }, new {@class = "btn btn-primary"})

    @if (HttpContext.Current.User.IsInRole("Admin"))
    {
        @Html.ActionLink("Add Reservatio", "CreateReservation", "AdminReservation", new {Area = "Admin"}, new {@class = "btn btn-primary"})
    }
</p>
<div id="hall-reservations"></div>

@section scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}

HRAgencySystem/HRAgencySystem.Web/Views/Hall/ShowReservations.cshtml
@using PagedList.Mvc
@model List<HRAgencySystem.Web.ViewModels.Hall.HallReservationsViewModel>
@{
    ViewBag.Title = "Show Rservations";
}

<h2>Show Reservations</h2>

<div id="hall-reservations-input" class="pull-left">
    @if (@Model.Any())
    {
        <table class="table table-striped table-hover table-hall-reservations" id="user-reservations">
            <thead>
            <tr>
                <th class="hidden-phone">Hall name</th>
                <th>Description</th>
                <th>Capacity</th>
                <th class="hidden-phone">Start date</th>
                <th class="hidden-phone">End date</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @Html.DisplayFor(x => x)
            </tbody>
        </table>
    }
    else
    {
        <p>No reservations!</p>
    }
</div>